<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-HR3H067" name="Rosters.roster_process" tests="8" failures="0" timestamp="12 Jun 2019 07:10:25 GMT" time="64.831" errors="1">
  <testcase name="Add_quantity" time="4.373" classname="Rosters.roster_process"/>
  <testcase name="Login" time="0.554" classname="Rosters.roster_process"/>
  <testcase name="Rosters" time="5.390" classname="Rosters.roster_process"/>
  <testcase name="Select_Roster" time="0.322" classname="Rosters.roster_process"/>
  <testcase name="Order_Acknowledgment" time="1.189" classname="Rosters.roster_process">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;...&gt; but was:&lt;... $183.65&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<...> but was:<... $183.65>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at Rosters.roster_process.Order_Acknowledgment(roster_process.java:194)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Order_Acknowledgment -->
  <testcase name="Add_Rosters" time="43.923" classname="Rosters.roster_process"/>
  <testcase name="Place_Order" time="7.330" classname="Rosters.roster_process"/>
  <testcase name="AddToCart" time="1.750" classname="Rosters.roster_process"/>
</testsuite> <!-- Rosters.roster_process -->
